swagger: '2.0'
host: grow.thingful.net
basePath: /api
schemes:
  - https
info:
  version: 0.1.1
  title: Thingful GROW Node HTTP API
  contact:
    name: Thingful
    url: 'https://thingful.net/site/contact/'
    email: dev@thingful.net
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  x-logo:
    url: ''
    backgroundColor: '#0033A0'
  description: >
    The Thingful GROW Node API is a HTTP API built according to the HydroNet4
    standards.


    <b>Clients must be authenticated in order to access the API.<br /> Please
    contact dev@thingful.net with any enquiries</b>

    <p>Base URL: https://grow.thingful.net/api</p>
security:
  - Bearer: []
securityDefinitions:
  Bearer:
    type: apiKey
    description: >-
      The Authorization header requires its value to be set to `Bearer `
      followed by the API key.
    in: header
    name: Authorization
